//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationForm()
        {
            this.FileDetails = new HashSet<FileDetail>();
        }
    
        public int ApplicationID { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string CustemerName { get; set; }
        public string Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Age { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public string PancardNumber { get; set; }
        public string AadhaarCardNumber { get; set; }
        public string PermanentAddress { get; set; }
        public string CurrentAddress { get; set; }
        public string LoanType { get; set; }
        public decimal RequiredLoanAmount { get; set; }
        public decimal RateOfInterest { get; set; }
        public int LoanTenureInMonth { get; set; }
        public decimal LoanEMI { get; set; }
        public string Summary { get; set; }
        public string LoanStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileDetail> FileDetails { get; set; }
    }
}
