//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMapping
    {
        public int Id { get; set; }
        public string LoanCode { get; set; }
        public string DocumentCode { get; set; }
    
        public virtual DocumentMaster DocumentMaster { get; set; }
        public virtual LoanType LoanType { get; set; }
    }
}
