//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanType()
        {
            this.DocumentMappings = new HashSet<DocumentMapping>();
        }
    
        public string LoanCode { get; set; }
        public string LoanDescription { get; set; }
        public decimal LoanInterestRatePerAnnum { get; set; }
        public decimal MinimumLoanAmount { get; set; }
        public decimal MaximumLoanAmount { get; set; }
        public int MinimumAgeRequired { get; set; }
        public int MaximumAgeRequired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentMapping> DocumentMappings { get; set; }
    }
}
